model:
  user:
    maximum_name: 255
    maximum_email: 255
    minimum_password: 6
    minimum_phone: 11
  post:
    size_title: 250
    size_content: 255
  comment:
    size_content: 45
controller:
  per_page: 10
size_gravater: 50
size_upload: 400
size_picture: 5
size_gravater_comment: 30
